---
- hosts: all
  become: true
  tasks:
    
    - name: Update packages
      apt:
         - update

    - name: Installing container runtime
      apt:
        name: docker.io 
        state: present 
        enabled: yes

    - name: Adding kubernetes signing key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Adding software Repositories
      shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Updating packages
      apt: 
        - update

    - name: Installing Kubernetes Tools
      apt:
        name: "{{ packages }}"
      vars:
        packages:
           - kubeadm
           - kubelet 
           - kubectl 
    
    - name: Marking the packages on hold 
      shell: apt-mark hold kubeadm kubelet kubectl

    - name: Setting Swap space off
      shell: sudo swapoff -a 

    