apiVersion: v1
kind: LimitRange
metadata: 
  name: memory-resource-constraint
spec:
  limits:
    - default:                                 #limit
        memory: 1Gi
      defaultRequest:                          # request
        memory: 1Gi
      max:
        memory: 1Gi                            # limit
      min:
        memory: 500Mi                            # request
      type: Container
