apiVersion: v1
kind: Namespace
metadata:
   name: dev

# commands
# kubectl create -f namespace-dev.yml
# kubectl create namespace dev
# kubectl get pods --namespace=prod
# kubectl config set-context $(kubectl config current-context) --namespace=dev 
# kubectl config set-context $(kubectl config current-context) --namespace=prod
# kubectl get pods --all-namespaces

# Resource Quota (to limit resouirce in a namespace)

apiVersion: v1
kind: ResourceQuota
metadata:
   name: compute-quota
   namespace: dev 
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi

# kubectl create -f compute-quota.yaml